on:
  label:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello World
        run: echo Hello, ${{ github.event.label.name}}

#      - name: Login to Docker Hub
#        uses: docker/login-action@v2.1.0
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_PASSWD }}

#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2

#      - name: Build and push
#        uses: docker/build-push-action@v3
#        with:
#          file: ./frontend/Dockerfile
#          push: true
#          tags: ${{ secrets.DOCKERHUB_USERNAME }}/test-frontend-pscfsa:${{ github.event.label.name}}
